/* =============================================================================
 * home.js — the Pixelstorm landing page
 *
 *   storm()    hero background: a Julia-set pixel shader running on the
 *              visitor's own GPU, steered by the pointer, with a live count
 *              of pixels shaded (the page's whole argument in one canvas)
 *   story()    scroll-driven explainer drawn from real RTL data
 *   minis()    live thumbnails in the bento grid
 *   gallery()  three framebuffers painted in the order the Verilog wrote them
 *
 * Data: web/data/site.json, generated by tools/site_data.js from the traces.
 * GSAP + ScrollTrigger are used when present; everything degrades gracefully.
 * ========================================================================== */
(function () {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const UI = window.PSUI; const reduce = UI.reduce;
  const G = window.gsap;
  const C = { blue: '#5B84FF', green: '#2DD4A0', amber: '#FFB938', magenta: '#FF4D8D', violet: '#A07DF0', cyan: '#38D6FF', tx: '#E8EEF6', tx2: '#9DADC1', tx3: '#64748A', edge: 'rgba(148,170,200,.18)' };
  const clamp = (x, a, b) => Math.max(a, Math.min(b, x));
  const ease = (t) => t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
  const lerp = (a, b, t) => a + (b - a) * t;
  const hex = (v) => '#' + (v & 0xffffff).toString(16).padStart(6, '0');
  function fitCanvas(cv, maxDpr = 2) {
    const d = Math.min(devicePixelRatio || 1, maxDpr); const w = cv.clientWidth, h = cv.clientHeight;
    if (cv.width !== Math.round(w * d) || cv.height !== Math.round(h * d)) { cv.width = Math.round(w * d); cv.height = Math.round(h * d); }
    const ctx = cv.getContext('2d'); ctx.setTransform(d, 0, 0, d, 0, 0); return { ctx, w, h };
  }
  function onVisible(el, cb) {   // run cb(true/false) as el enters/leaves the viewport
    if (!('IntersectionObserver' in window)) { cb(true); return; }
    new IntersectionObserver((es) => es.forEach(e => cb(e.isIntersecting)), { rootMargin: '100px' }).observe(el);
  }
  function roundRect(ctx, x, y, w, h, r, fill, stroke) {
    ctx.beginPath(); ctx.moveTo(x + r, y); ctx.arcTo(x + w, y, x + w, y + h, r); ctx.arcTo(x + w, y + h, x, y + h, r); ctx.arcTo(x, y + h, x, y, r); ctx.arcTo(x, y, x + w, y, r); ctx.closePath();
    if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = 1.5; ctx.stroke(); }
  }

  // ===========================================================================
  // 1. hero: a pixel shader running on the visitor's GPU
  // ===========================================================================
  function storm() {
    const cv = $('storm');
    const gl = cv.getContext('webgl', { antialias: false, powerPreference: 'high-performance', preserveDrawingBuffer: false });
    const fallback = () => { cv.hidden = true; document.querySelector('.storm-fallback').hidden = false; };
    if (!gl) { fallback(); return; }
    const VS = 'attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';
    const FS = `precision highp float;
uniform vec2 uRes; uniform float uTime; uniform vec2 uMouse; uniform float uCell;
vec3 pal(float t){ return .5 + .5 * cos(6.28318 * (t + vec3(.58, .68, .80))); }   // cyan / blue / violet / magenta
void main(){
  vec2 cell = floor(gl_FragCoord.xy / uCell) * uCell + .5 * uCell;       // shade per "pixel" cell
  vec2 uv = (cell - vec2(.72, .5) * uRes) / uRes.y;
  float a = uTime * .06;
  vec2 c = vec2(-.8, .156) + .02 * vec2(cos(a * 1.3), sin(a)) + (uMouse - .5) * vec2(.06, .045);
  float rot = .15 * sin(a * .5); mat2 R = mat2(cos(rot), -sin(rot), sin(rot), cos(rot));
  vec2 z = R * uv * 2.8;
  float i = 0.; float m = 0.;
  for (int k = 0; k < 160; k++) { z = vec2(z.x*z.x - z.y*z.y, 2.*z.x*z.y) + c; m = dot(z, z); if (m > 1024.) break; i += 1.; }
  vec3 col = vec3(.015, .02, .045);
  if (i < 160.) {
    float s = i - log2(log2(m) / log2(1024.)) ;          // smooth iteration count
    float t = clamp(s / 60., 0., 1.);
    float glow = pow(t, .9);
    col = mix(col, pal(t * 1.4 + uTime * .01) * 1.15, smoothstep(.02, .5, glow));
    col += vec3(.9, .95, 1.) * pow(t, 5.) * .8;          // hot white filaments
  } else col = vec3(.03, .02, .08);
  vec2 g = fract(gl_FragCoord.xy / uCell);                // faint pixel grid
  col *= .86 + .14 * step(.1, g.x) * step(.1, g.y);
  gl_FragColor = vec4(col, 1.);
}`;
    const sh = (type, src) => { const s = gl.createShader(type); gl.shaderSource(s, src); gl.compileShader(s); if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(s)); return s; };
    const prog = gl.createProgram();
    try { gl.attachShader(prog, sh(gl.VERTEX_SHADER, VS)); gl.attachShader(prog, sh(gl.FRAGMENT_SHADER, FS)); gl.linkProgram(prog); }
    catch (e) { console.warn(e); fallback(); return; }
    gl.useProgram(prog);
    const buf = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, buf);
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1, -1, 3, -1, -1, 3]), gl.STATIC_DRAW);
    const loc = gl.getAttribLocation(prog, 'p'); gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc, 2, gl.FLOAT, false, 0, 0);
    const U = (n) => gl.getUniformLocation(prog, n);
    const uRes = U('uRes'), uTime = U('uTime'), uMouse = U('uMouse'), uCell = U('uCell');
    let mouse = [0.5, 0.5], target = [0.5, 0.5], shaded = 0, visible = true; const t0 = performance.now();
    addEventListener('pointermove', (e) => { target = [e.clientX / innerWidth, 1 - e.clientY / innerHeight]; }, { passive: true });
    onVisible(cv, (v) => { visible = v; });
    const counter = $('pxCount');
    function frame(now) {
      const d = Math.min(devicePixelRatio || 1, 1.5);
      const w = Math.round(cv.clientWidth * d), h = Math.round(cv.clientHeight * d);
      if (cv.width !== w || cv.height !== h) { cv.width = w; cv.height = h; gl.viewport(0, 0, w, h); }
      if (visible && !document.hidden) {
        mouse = [lerp(mouse[0], target[0], 0.04), lerp(mouse[1], target[1], 0.04)];
        gl.uniform2f(uRes, w, h); gl.uniform1f(uTime, reduce ? 12 : (now - t0) / 1000);
        gl.uniform2f(uMouse, mouse[0], mouse[1]); gl.uniform1f(uCell, Math.max(2, Math.round(3 * d)));
        gl.drawArrays(gl.TRIANGLES, 0, 3);
        shaded += w * h; counter.textContent = shaded.toLocaleString('en-US');
      }
      if (!reduce) requestAnimationFrame(frame);
    }
    requestAnimationFrame(frame);
  }

  // ===========================================================================
  // 2. instruction marquee
  // ===========================================================================
  function marquees(site) {
    const isa = site.isa || [];
    const chip = (e) => `<span class="chipi ${e.group}"><b>${e.name}</b>${e.cuda.split(';')[0].replace(/^PTX /, '')}</span>`;
    const half = Math.ceil(isa.length / 2);
    $('mq1').innerHTML = isa.slice(0, half).map(chip).join('');
    $('mq2').innerHTML = isa.slice(half).map(chip).join('');
    UI.marquees();
  }

  // ===========================================================================
  // 3. the story: one thread -> warp -> grid -> paint -> divergence
  // ===========================================================================
  function story(site) {
    const P = site.paint && site.paint.mandelbrot; const cv = $('storyCanvas'); const hud = $('storyHud');
    if (!P) return;
    const Wd = P.width, Ht = P.height, N = Wd * Ht, MAXIT = 12;
    const iters = P.color.map(v => v === 0 ? MAXIT : ((v >> 8) & 255) / 10);
    const idle = new Array(N).fill(0); let useful = 0, slots = 0;
    for (let y = 0; y < Ht; y++) for (let w0 = 0; w0 < Wd; w0 += 8) {
      let mx = 0; for (let x = w0; x < w0 + 8; x++) mx = Math.max(mx, iters[y * Wd + x]);
      for (let x = w0; x < w0 + 8; x++) { const i = y * Wd + x; idle[i] = (mx - iters[i]) / (mx + 1); useful += iters[i] + 1; slots += mx + 1; }
    }
    const eff = Math.round(100 * useful / slots);
    // zoom into the most colourful warp: the one with the widest spread of iteration counts
    let FY = 0, FW = 0, best = -1;
    for (let y = 0; y < Ht; y++) for (let w0 = 0; w0 < Wd; w0 += 8) {
      const v = new Set(); for (let x = w0; x < w0 + 8; x++) v.add(iters[y * Wd + x]);
      const score = v.size * 10 - Math.abs(y - Ht / 2);
      if (score > best) { best = score; FY = y; FW = w0; }
    }
    let FL = 0; for (let k = 0; k < 8; k++) if (iters[FY * Wd + FW + k] < MAXIT && iters[FY * Wd + FW + k] > iters[FY * Wd + FW + FL] * (iters[FY * Wd + FW + FL] >= MAXIT ? 0 : 1)) FL = k;
    const focus = FY * Wd + FW + FL;
    const PROG = ['S2R   R0, TID', 'MAD   R2, R0, R9, R2', 'QMUL  R7, R4, R4', 'QMUL  R8, R5, R5', 'SETP.GT P0, R9, R10', '@P0 BRA done', 'ADD   R4, R4, R2', 'STG   [R13], R7'];
    let cur = 0, target = 0, active = false;
    const steps = [...document.querySelectorAll('.story .step')];
    const measure = () => {
      const r = document.querySelector('.story-steps').getBoundingClientRect();
      return clamp((innerHeight * 0.5 - r.top - innerHeight * 0.18) / (r.height - innerHeight * 0.48), 0, 1) * 4.999;
    };
    if (G && window.ScrollTrigger && !reduce) {
      G.registerPlugin(window.ScrollTrigger);
      window.ScrollTrigger.create({ trigger: '.story-steps', start: 'top top', end: 'bottom bottom', onUpdate: () => { target = measure(); } });
    }
    addEventListener('scroll', () => { target = measure(); }, { passive: true });
    target = cur = measure();
    onVisible(cv, (v) => { active = v; if (v) requestAnimationFrame(loop); });
    window.PSHOME = { setStory: (p) => { target = cur = p; draw(p, 1); } };

    function loop(now) {
      if (!active) return;
      cur = reduce ? target : lerp(cur, target, 0.09);
      draw(cur, now / 1000);
      steps.forEach((s, i) => s.classList.toggle('on', Math.min(4, Math.floor(cur + 0.5)) === i));
      requestAnimationFrame(loop);
    }
    function draw(p, time) {
      const { ctx, w, h } = fitCanvas(cv);
      ctx.clearRect(0, 0, w, h);
      const cs = Math.min((w - 90) / Wd, (h - 110) / Ht); const gx = (w - cs * Wd) / 2 + 20, gy = (h - cs * Ht) / 2 - 18;
      const grid = (i) => [gx + (i % Wd) * cs, gy + Math.floor(i / Wd) * cs];
      const lane = Math.min((w - 80) / 8.8, 84); const lx0 = (w - lane * 8 - 6 * 7) / 2, ly = h * 0.46;
      const laneXY = (k) => [lx0 + k * (lane + 6), ly];
      const s = Math.floor(p), f = ease(p - s);
      const warpIdx = (k) => FY * Wd + FW + k;
      ctx.font = '600 13px "JetBrains Mono", monospace'; ctx.textBaseline = 'middle';
      let hudTxt = '';
      if (s === 0) {                       // --- one thread
        const big = lerp(Math.min(w, h) * 0.3, lane, f); const [tx, ty] = laneXY(FL);
        const x = lerp(w * 0.28 - big / 2, tx, f), y = lerp(h * 0.44 - big / 2, ty, f);
        for (let k = 0; k < 8; k++) if (k !== FL) { const [lx, lyy] = laneXY(k); ctx.globalAlpha = f; roundRect(ctx, lx, lyy, lane, lane, 10, hex(P.color[warpIdx(k)]), C.edge); ctx.globalAlpha = 1; }
        roundRect(ctx, x, y, big, big, 14, hex(P.color[focus]), 'rgba(255,255,255,.6)');
        ctx.globalAlpha = 1 - f;
        const pc = Math.floor(time * 1.6) % PROG.length; const px = w * 0.28 + Math.min(w, h) * 0.2, py = h * 0.44 - PROG.length * 11;
        PROG.forEach((l, i) => { ctx.fillStyle = i === pc ? C.cyan : C.tx3; ctx.fillText((i === pc ? '> ' : '  ') + l, px, py + i * 22); });
        ctx.fillStyle = C.tx2; ctx.font = '600 15px "Barlow", sans-serif';
        ctx.fillText(`thread (x = ${FW + FL}, y = ${FY}): its own registers, the same program`, 24, h * 0.44 + Math.min(w, h) * 0.2);
        ctx.globalAlpha = 1;
        hudTxt = `<span>1 thread</span><span>1 pixel</span><span>color <b>${hex(P.color[focus])}</b></span>`;
      } else if (s === 1) {                // --- one warp, lockstep
        const pc = Math.floor(time * 1.6) % PROG.length;
        ctx.globalAlpha = f; drawGrid(ctx, grid, cs, false); ctx.globalAlpha = 1;
        for (let k = 0; k < 8; k++) {
          const i = warpIdx(k); const [lx, lyy] = laneXY(k); const [ax, ay] = grid(i);
          const x = lerp(lx, ax, f), y = lerp(lyy, ay, f), sz = lerp(lane, cs, f);
          roundRect(ctx, x, y, sz, sz, lerp(10, 2, f), hex(P.color[i]), 'rgba(255,255,255,.35)');
          if (f < 0.4) { ctx.globalAlpha = 1 - f / 0.4; ctx.fillStyle = C.tx2; ctx.font = '600 12px "JetBrains Mono", monospace'; ctx.textAlign = 'center'; ctx.fillText(`lane ${k}`, x + sz / 2, y + sz + 16); ctx.fillText(`it=${iters[i]}`, x + sz / 2, y + sz + 34); ctx.textAlign = 'left'; ctx.globalAlpha = 1; }
        }
        ctx.globalAlpha = 1 - f;
        const bx = lx0, by = ly - 70, bw = lane * 8 + 42;
        roundRect(ctx, bx, by, bw, 42, 10, 'rgba(91,132,255,.18)', C.blue);
        ctx.fillStyle = C.tx; ctx.font = '600 14px "JetBrains Mono", monospace'; ctx.fillText('all 8 lanes:  ' + PROG[pc], bx + 16, by + 21);
        for (let k = 0; k < 8; k++) { const [lx] = laneXY(k); ctx.strokeStyle = 'rgba(91,132,255,.5)'; ctx.beginPath(); ctx.moveTo(lx + lane / 2, by + 42); ctx.lineTo(lx + lane / 2, ly - 4); ctx.stroke(); }
        ctx.globalAlpha = 1;
        hudTxt = '<span>1 warp</span><span>8 lanes</span><span>fetch + decode once, execute 8 times</span>';
      } else if (s === 2) {                // --- grid, blocks, SMs
        drawGrid(ctx, grid, cs, true, f);
        hudTxt = `<span><b>512</b> threads</span><span><b>64</b> warps</span><span><b>16</b> blocks</span><span style="color:${C.blue}">&#9632; SM 0</span><span style="color:${C.violet}">&#9632; SM 1</span>`;
      } else {                             // --- paint (3) and divergence (4)
        const tNow = s === 3 ? f * P.cycles : P.cycles;
        let n0 = 0, n1 = 0;
        for (let i = 0; i < N; i++) {
          const [x, y] = grid(i);
          if (P.t[i] <= tNow) {
            ctx.fillStyle = hex(P.color[i]); ctx.fillRect(x, y, cs - 1, cs - 1);
            if (P.sm[i]) n1++; else n0++;
            if (s === 3 && tNow - P.t[i] < P.cycles * 0.02) { ctx.strokeStyle = '#fff'; ctx.lineWidth = 1.5; ctx.strokeRect(x + 1, y + 1, cs - 3, cs - 3); }
            if (s === 4 && idle[i] > 0.01) { ctx.fillStyle = `rgba(255,77,141,${(0.15 + 0.75 * idle[i]) * f})`; ctx.fillRect(x, y, cs - 1, cs - 1); }
          } else { ctx.fillStyle = ((i + Math.floor(i / Wd)) & 1) ? '#111925' : '#0C121B'; ctx.fillRect(x, y, cs - 1, cs - 1); }
        }
        ctx.strokeStyle = s === 4 ? `rgba(255,255,255,${0.15 + 0.35 * f})` : 'rgba(255,255,255,.12)'; ctx.lineWidth = 1;
        for (let y = 0; y < Ht; y++) for (let x = 0; x < Wd; x += 8) { const [a, b] = grid(y * Wd + x); ctx.strokeRect(a - 0.5, b - 0.5, cs * 8, cs); }
        hudTxt = s === 3 ? `<span>cycle <b>${Math.round(tNow).toLocaleString('en-US')}</b> / ${P.cycles.toLocaleString('en-US')}</span><span style="color:${C.blue}">SM 0 <b>${n0}</b> px</span><span style="color:${C.violet}">SM 1 <b>${n1}</b> px</span>`
          : `<span>loop iterations needed vs issued: <b>${eff}%</b></span><span style="color:${C.magenta}">&#9632; idle lanes</span><span>warps outlined</span>`;
      }
      hud.innerHTML = hudTxt;
    }
    function drawGrid(ctx, grid, cs, sm, f = 1) {
      for (let i = 0; i < N; i++) {
        const [x, y] = grid(i); const blk = Math.floor(i / Wd);
        const smc = P.sm[blk * Wd] ? 'rgba(160,125,240,' : 'rgba(91,132,255,';
        ctx.fillStyle = sm ? smc + (0.12 + 0.28 * f) + ')' : '#0E1520';
        ctx.fillRect(x, y, cs - 1, cs - 1);
      }
      ctx.strokeStyle = 'rgba(255,255,255,.22)'; ctx.lineWidth = 1;
      for (let y = 0; y < Ht; y++) for (let x = 0; x < Wd; x += 8) { const [a, b] = grid(y * Wd + x); ctx.strokeRect(a - 0.5, b - 0.5, cs * 8, cs); }
      if (sm && f > 0.3) {
        ctx.globalAlpha = (f - 0.3) / 0.7; ctx.fillStyle = C.tx2; ctx.font = '600 11px "JetBrains Mono", monospace';
        for (let y = 0; y < Ht; y += 3) { const [a, b] = grid(y * Wd); ctx.fillText(`block ${y}`, a - 64, b + cs / 2); }
        ctx.globalAlpha = 1;
      }
    }
  }

  // ===========================================================================
  // 4. bento minis
  // ===========================================================================
  function minis(site) {
    // framebuffer: the triangle, painted in RTL order, looping
    const T = site.paint && site.paint.triangle_raster; const fb = $('miniFb');
    let fbOn = false; onVisible(fb, v => { fbOn = v; if (v) requestAnimationFrame(fbLoop); });
    function fbLoop(now) {
      if (!fbOn || !T) return;
      const ctx = fb.getContext('2d'); const S = fb.width / T.width;
      const ph = ((now / 1000) % 6) / 4.5; const tNow = reduce ? T.cycles : clamp(ph, 0, 1) * T.cycles;
      for (let i = 0; i < T.color.length; i++) {
        const x = (i % T.width) * S, y = Math.floor(i / T.width) * S;
        ctx.fillStyle = T.t[i] <= tNow ? hex(T.color[i]) : (((i + Math.floor(i / T.width)) & 1) ? '#111925' : '#0C121B');
        ctx.fillRect(x, y, S, S);
      }
      if (!reduce) requestAnimationFrame(fbLoop);
    }
    // lanes: lockstep, split, rejoin
    const svg = $('miniLanes'); const NS = 'http://www.w3.org/2000/svg';
    const ODD = 0b10101010, EVEN = 0b01010101, ALL = 0xff;
    const prog = [['S2R  R0, TID', ALL, 'ctl'], ['ANDI R1, R0, 1', ALL, 'exe'], ['@!P0 BRA else', ALL, 'ctl'], ['MULI R2, R0, 3', ODD, 'exe'], ['BRA  join', ODD, 'ctl'], ['SHRI R2, R0, 1', EVEN, 'exe'], ['LDG  R3, [R4]', ALL, 'mem'], ['EXIT', ALL, 'ctl']];
    const caps = ['All 8 lanes, one instruction.', 'Every lane on its own data.', 'Lanes disagree: the warp splits.', 'Odd lanes run; even lanes wait.', 'Odd lanes jump to the join...', '...then even lanes run.', 'Back in lockstep at the join.', 'Done.'];
    const col = { ctl: C.blue, exe: C.green, mem: C.amber };
    let step = reduce ? 5 : 0;
    function lanesTick() {
      svg.innerHTML = '';
      const add = (tag, a, txt) => { const e = document.createElementNS(NS, tag); for (const k in a) e.setAttribute(k, a[k]); if (txt !== undefined) e.textContent = txt; svg.appendChild(e); return e; };
      const first = Math.max(0, step - 4);
      for (let i = first; i <= step; i++) {
        const [txt, mask, kind] = prog[i]; const y = 12 + (i - first) * 38; const curr = i === step;
        add('text', { x: 8, y: y + 20, fill: curr ? C.tx : C.tx3, 'font-size': 11.5, 'font-family': 'JetBrains Mono, monospace' }, txt);
        for (let l = 0; l < 8; l++) {
          const on = (mask >> l) & 1;
          add('rect', { x: 128 + l * 23, y: y + 6, width: 19, height: 22, rx: 4, fill: on ? col[kind] : 'rgba(255,77,141,.15)', stroke: on ? 'none' : C.magenta, 'stroke-dasharray': on ? '' : '3 2', opacity: curr ? 1 : 0.45 });
        }
      }
      $('lanesCap').textContent = caps[step];
      step = (step + 1) % prog.length;
    }
    lanesTick(); if (!reduce) setInterval(lanesTick, 1300);
    // coalescing: lanes -> 4-word lines, three patterns
    const cc = $('miniCoal'); let con = false; onVisible(cc, v => { con = v; if (v) requestAnimationFrame(coalLoop); });
    const pats = [['in[i]: 2 transactions', l => l], ['in[4i]: 8 transactions', l => 4 * l], ['in[0]: 1 transaction', () => 0]];
    const tcol = [C.green, C.amber, C.blue, C.violet, C.magenta, C.cyan, '#FF8A3D', '#9BE15D'];
    function coalLoop(now) {
      if (!con) return;
      const ctx = cc.getContext('2d'); const w = cc.width, h = cc.height; ctx.clearRect(0, 0, w, h);
      const k = Math.floor(now / 2600) % 3; const ph = reduce ? 1 : (now % 2600) / 2600; const [name, f] = pats[k];
      const lines = []; const txn = [];
      for (let l = 0; l < 8; l++) { const ln = f(l) & ~3; if (!lines.includes(ln)) lines.push(ln); txn.push(lines.indexOf(ln)); }
      ctx.font = '600 12px JetBrains Mono, monospace'; ctx.fillStyle = C.tx2; ctx.textBaseline = 'alphabetic'; ctx.fillText(name, 10, 18);
      const cw = (w - 20) / 32;
      for (let a = 0; a < 32; a++) { const li = lines.indexOf(a & ~3); ctx.fillStyle = li >= 0 ? tcol[li % 8] + '88' : '#111925'; ctx.fillRect(10 + a * cw, h - 34, cw - 1.5, 20); }
      for (let l = 0; l < 8; l++) {
        const x = 12 + l * ((w - 24) / 8); const lw = (w - 24) / 8 - 6;
        roundRect(ctx, x, 30, lw, 22, 5, tcol[txn[l] % 8]);
        ctx.fillStyle = '#05070B'; ctx.fillText(`L${l}`, x + 6, 45);
        const a = f(l); const tx = 10 + a * cw + cw / 2; const e = ease(clamp(ph * 1.6 - txn[l] * 0.12, 0, 1));
        ctx.fillStyle = tcol[txn[l] % 8]; ctx.beginPath(); ctx.arc(lerp(x + lw / 2, tx, e), lerp(56, h - 38, e), 3.5, 0, 7); ctx.fill();
      }
      if (!reduce) requestAnimationFrame(coalLoop);
    }
    // code roll: real lines from rtl/ps_sm.v
    const code = (site.rtl || '').split('\n').map(l => l.replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/(\/\/.*)$/, '<span class="cm">$1</span>').replace(/\b(always|begin|end|if|for|else|wire|reg|assign|integer)\b/g, '<span class="kw">$1</span>')
      .replace(/\b(w_minpc|pick_act|bar_release|lpc|ldone|w_wait|rr_ptr)\b/g, '<span class="nm">$1</span>')).join('\n');
    $('codeRoll').innerHTML = code + '\n' + code;
    // test terminal typing
    const lines = (site.kernels || []).map(k => `<span class="pass">PASS</span> ${k.name.padEnd(18)} ${String(k.cycles).padStart(6)} cyc ${String(k.simd).padStart(5)}%`);
    const term = $('testTerm'); let li = reduce ? lines.length : 0;
    function termTick() { const shown = lines.slice(Math.max(0, li - 7), li + 1); term.innerHTML = shown.join('\n') + (li >= lines.length - 1 ? '\n<span class="pass">all kernels match: RTL == model</span>' : ''); li = (li + 1) % (lines.length + 3); }
    termTick(); if (!reduce) setInterval(termTick, 700);
  }

  // ===========================================================================
  // 5. gallery: scrub through the simulation
  // ===========================================================================
  function gallery(site) {
    const cvs = [...document.querySelectorAll('.gal-grid canvas')];
    let prog = 0, playing = !reduce, mode = 'color', last = performance.now(), visible = false;
    const scrub = $('galScrub'), pct = $('galPct'), btn = $('galPlay');
    const heat = (t) => { const a = [[56, 214, 255], [91, 132, 255], [160, 125, 240], [255, 77, 141], [255, 185, 56]]; const x = t * (a.length - 1), i = Math.min(a.length - 2, Math.floor(x)), f = x - i; return `rgb(${a[i].map((v, k) => Math.round(lerp(v, a[i + 1][k], f))).join(',')})`; };
    function draw() {
      for (const cv of cvs) {
        const D = site.paint && site.paint[cv.dataset.k]; if (!D) continue;
        const ctx = cv.getContext('2d'); const S = cv.width / D.width; const tNow = Math.min(prog, 1) * D.cycles;
        for (let i = 0; i < D.color.length; i++) {
          const x = (i % D.width) * S, y = Math.floor(i / D.width) * S; const done = D.t[i] <= tNow;
          ctx.fillStyle = !done ? ((((i % D.width) + Math.floor(i / D.width)) & 1) ? '#111925' : '#0C121B')
            : mode === 'color' ? hex(D.color[i]) : mode === 'sm' ? (D.sm[i] ? C.violet : C.blue) : heat(D.t[i] / D.cycles);
          const gap = mode === 'color' ? 0 : 1;
          ctx.fillRect(x, y, S - gap, S - gap);
          if (done && tNow - D.t[i] < D.cycles * 0.015 && prog < 1) { ctx.strokeStyle = 'rgba(255,255,255,.9)'; ctx.lineWidth = 1.5; ctx.strokeRect(x + 1, y + 1, S - 2, S - 2); }
        }
      }
      scrub.value = Math.round(Math.min(prog, 1) * 1000); pct.textContent = Math.round(Math.min(prog, 1) * 100) + '%';
    }
    function loop(now) {
      const dt = (now - last) / 1000; last = now;
      if (playing && visible) { prog += dt / 7; if (prog > 1.15) prog = 0; draw(); }
      requestAnimationFrame(loop);
    }
    onVisible($('gallery'), v => { visible = v; if (v) draw(); });
    scrub.addEventListener('input', () => { prog = scrub.value / 1000; playing = false; btn.textContent = 'Play'; draw(); });
    btn.addEventListener('click', () => { playing = !playing; btn.textContent = playing ? 'Pause' : 'Play'; if (playing && prog >= 1) prog = 0; });
    btn.textContent = playing ? 'Pause' : 'Play';
    document.querySelectorAll('.seg button').forEach(b => b.addEventListener('click', () => {
      mode = b.dataset.mode;
      document.querySelectorAll('.seg button').forEach(x => { x.classList.toggle('on', x === b); x.setAttribute('aria-checked', String(x === b)); });
      draw();
    }));
    if (reduce) prog = 1;
    draw();
    requestAnimationFrame(loop);
  }

  // ===========================================================================
  function heroIntro() {
    if (!G || reduce) return;
    document.querySelectorAll('.hero [data-reveal]').forEach(e => { e.removeAttribute('data-reveal'); });
    G.from('.hero-inner > *', { y: 30, opacity: 0, duration: 1, stagger: 0.12, ease: 'power3.out', delay: 0.15 });
    if (window.ScrollTrigger) {
      G.registerPlugin(window.ScrollTrigger);
      G.to('.hero-inner', { y: -80, opacity: 0.15, ease: 'none', scrollTrigger: { trigger: '.hero', start: 'top top', end: 'bottom top', scrub: true } });
    }
  }
  document.addEventListener('DOMContentLoaded', async () => {
    heroIntro();
    UI.init();
    storm();
    let site = {};
    try { site = await (await fetch('data/site.json')).json(); } catch (e) { console.warn('data/site.json not found; run make site'); }
    marquees(site); story(site); minis(site); gallery(site);
  });
})();
